[package]
name = "git-authors"
version = "0.1.0"
edition = "2024"

[dependencies]
git2 = "0.20.2"
octocrab = "0.44.1"
regex = "1.11.1"
tempfile = "3.20.0"
tokio = { version = "1.47.1", features = ["full"] }
